home:
    method: 'get'
    path: '/'
    handler: 'Default::index'

post:
    method: 'post'
    path: '/'
    handler: 'Default::post'

info:
    method: 'get'
    path: '/info'
    handler: 'Default::info'

delete:
    method: 'get'
    path: '/delete'
    handler: 'Default::delete'
